version: '3'
services:
  aliyun-hub:
    image: zelejs/allin-web:jdk11
    privileged: true
    container_name: aliyun-hub
    volumes:
      - ./api:/webapps
      - /host/sandbox/nginx/attachments:/attachments  ## set host /host/sandbox/nginx/attachments
networks:
  default:
    external:
      name: ${network}   ## host docker network 
