version: '3'
services:
  aliyun-hub:
    image: zelejs/allin-web:jdk11
    privileged: true
    container_name: aliyun-hub
    volumes:
      - ./api:/webapps
      - ./attachments:/attachments  ## set host /host/sandbox/nginx/attachments
    #environment:
    #    DL_STANDALONE: "aliyun-hub-1.0.0-standalone.jar"
  aliyun-hub-dl:
    container_name: aliyun-hub-dl
    privileged: true
    image: 'daocloud.io/library/nginx:latest'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./images:/usr/share/nginx/html/images
      - ./attachments:/usr/share/nginx/html/attachments
networks:
  default:
    external:
      name: ${network}   ## host docker network 
