version: '3'
services:
  aliyun-hub:
    image: zelejs/app-openjre11
    container_name: aliyun-hub
    volumes:
      - ./api:/webapps
      - ./attachments:/attachments
    ports:
      - '8080:8080'
networks:
  default:
    external:
      name: ${network}
