version: '3'
services:
  aliyun-hub:
    image: zelejs/allin-web:jdk11
    privileged: true
    container_name: aliyun-hub
    volumes:
      - ./api:/webapps
      - ./nginx/attachments:/attachments

  aliyun-hub-nginx:
    container_name: aliyun-hub-nginx
    privileged: true
    image: 'daocloud.io/library/nginx:latest'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/images:/usr/share/nginx/html/images
      - ./nginx/attachments:/usr/share/nginx/html/attachments
    environment:
      TZ: "Asia/Shanghai"

networks:
  default:
    external:
      name: ${network}   ## app docker network 